#!/bin/sh 
#
#----------------------------------------------
#Copyright (C) 2019 Twinzo1 <1282055288@qq.com>
#----------------------------------------------
#
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@watchpig[0]
	add ucitrack watchpig
    	set ucitrack.@watchpig[0].init=watchpig
    	commit ucitrack
	set watchpig.@mac[0].interface="wan"
	set watchpig.@mac[0]."$(uci -q get network.wan_dev)"="wan_dev"
	set watchpig.@mac[0].macaddr="$(uci -q get network.wan.macaddr||uci -q get network.wan_dev.macaddr)"
	commit mac
    EOF
rm -f /tmp/luci-indexcache
exit 0
