#!/bin/sh 
#
#----------------------------------------------
#Copyright (C) 2019 Twinzo1 <1282055288@qq.com>
#----------------------------------------------
#
uci -q batch <<-EOT
	set mac.@mac[0].macc="$(uci -q get network.wan.macaddr||uci -q get network.wan_dev.macaddr)"
	commit mac
    EOT

exit 0
