#!/bin/sh /etc/rc.common
#(c) 2010 ivan_wl
START=99
start() {
	macaddr=$(uci get mac.@mac[0].macaddr 2>/dev/null)

	if [ -n "$macaddr" ]; then
		uci set network.wan.macaddr="$macaddr"
		uci set network.wan6.macaddr="$macaddr"
		uci commit
		/etc/init.d/network restart
	fi

}
reload() {	
	ipaddr=$(uci get mac.@mac[0].ipaddr 2>/dev/null)

	if [ -n "$ipaddr" ]; then
		uci set mac.@mac[0].ipaddr="$ipaddr"
		uci commit
	fi
}