#!/bin/sh /etc/rc.common
#(c) 2010 ivan_wl
START=90

start() {
	curdir=/etc/dogcom.conf
	touch $curdir
	tmp_server="server= '$(uci get dogcom.@dogcom[0].server )'"
	tmp_pppoe_flag="pppoe_flag='$(uci get dogcom.@dogcom[0].pppoe_flag )'"
	tmp_keep_alive2_flag="keep_alive2_flag='$(uci get dogcom.@dogcom[0].keep_alive2_flag )'"
	tmp_username="username = '$(uci get dogcom.@dogcom[0].username)'"
	tmp_password="password = '$(uci get dogcom.@dogcom[0].password)'"			
	tmp_host_name="host_name = '$(uci get dogcom.@dogcom[0].host_name)'"
	tmp_host_os="host_os = '$(uci get dogcom.@dogcom[0].host_os)'"
	tmp_host_ip="host_ip = '$(uci get dogcom.@dogcom[0].host_ip)'"
	tmp_dhcp_server="dhcp_server = '$(uci get dogcom.@dogcom[0].dhcp_server)'"
	tmp_mac="mac = $(uci get dogcom.@dogcom[0].mac)"
	tmp_PRIMARY_DNS="PRIMARY_DNS = '$(uci get dogcom.@dogcom[0].PRIMARY_DNS)'"
	tmp_AUTH_VERSION="AUTH_VERSION = '$(uci get dogcom.@dogcom[0].AUTH_VERSION)'"
	tmp_KEEP_ALIVE_VERSION="KEEP_ALIVE_VERSION = '$(uci get dogcom.@dogcom[0].KEEP_ALIVE_VERSION)'"
	tmp_CONTROLCHECKSTATUS="CONTROLCHECKSTATUS = '$(uci get dogcom.@dogcom[0].CONTROLCHECKSTATUS)'"
	tmp_ADAPTERNUM="ADAPTERNUM = '$(uci get dogcom.@dogcom[0].ADAPTERNUM)'"
	tmp_IPDOG="IPDOG = '$(uci get dogcom.@dogcom[0].IPDOG)'"
	
	enable=$(uci get dogcom.@dogcom[0].enable 2>/dev/null)
	version=$(uci get dogcom.@dogcom[0].version 2>/dev/null)
	enabledial=$(uci get dogcom.@dogcom[0].enabledial 2>/dev/null)
	ifname=$(uci get network.wan6.ifname 2>/dev/null)
	user=$(uci get dogcom.@dogcom[0].user 2>/dev/null)
	pwd=$(uci get dogcom.@dogcom[0].pwd 2>/dev/null)
	macaddr=$(uci get dogcom.@dogcom[0].macaddr 2>/dev/null)	

	if [ "$enable"x = "1"x ]; then
		/etc/init.d/dogcom enable
	else
		/etc/init.d/dogcom disable
		killall dogcom
		return
	fi

	if [ "$enabledial"x != "0"x ]; then
#		echo "$ifname" "$user" "$pwd"
		uci set network.wan.ifname="$ifname"
		uci set network.wan.proto="pppoe"
		uci set network.wan.username="$user"
		uci set network.wan.password="$pwd"
		uci commit
	fi
	
	if ["$version" = "P"]; then
		"$drcom_version" = "pppoe"
		echo "当前为P版"
		echo $tmp_server > $curdir
		echo "$tmp_pppoe_flag" >> "$curdir"
		echo "$tmp_keep_alive2_flag" >> "$curdir"
	else
		"$drcom_version" = "dhcp"
		echo "当前为D版"
		echo $tmp_server > $curdir
		echo $tmp_username >> $curdir
		echo $tmp_password >> $curdir
		echo $tmp_host_name >> $curdir
		echo $tmp_host_os >> $curdir
		echo $tmp_host_ip >> $curdir
		echo $tmp_dhcp_server >> $curdir
		echo $tmp_mac >> $curdir
		echo $tmp_PRIMARY_DNS >> $curdir
		echo $tmp_AUTH_VERSION >> $curdir
		echo $tmp_KEEP_ALIVE_VERSION >> $curdir
		echo $tmp_CONTROLCHECKSTATUS >> $curdir
		echo $tmp_ADAPTERNUM >> $curdir
		echo $tmp_IPDOG >> $curdir
	fi

	if [ -n "$macaddr" ]; then
		uci set network.wan.macaddr="$macaddr"
		uci set network.wan6.macaddr="$macaddr"
		uci set network.wan_dev.macaddr="$macaddr"
		uci commit
	fi

	if [ -n "$macaddr" -o "$enabledial"x != "0"x ]; then
		/etc/init.d/network restart
	fi

	if [ -n "$server" ]; then
		config_server="server=$server"
	fi
	
	if [ -n "$pppoe_flag" ]; then
		config_pppoe_flag="--pppoe-flag=$pppoe_flag"
	fi
	
	if [ -n "$keep_alive2_flag" ]; then
		config_keep_alive2_flag="--keep-alive2-flag=$keep_alive2_flag"
	fi
	
	echo "Dr.COM Client is started"
	dogcom -m $drcom_version -c /etc/dogcom.conf -e -d -l /tmp/dogcom.log
	
}
stop()
{
	echo "Dr.COM Client is stopped"
	killall dogcom
		
	return 0
}