#!/bin/sh /etc/rc.common
#Cpyright by Twizo<1282055288@qq.com>
START=90

stochastic(){
	echo `dd if=/dev/urandom bs=1 count=32 2>/dev/null | md5sum | cut -b 0-12 | sed 's/\(..\)/\1:/g; s/.$//'`
}

sto(){ 
	local stom=$("stochastic")
	uci set network.wan.macaddr="$stom"
	uci set network.wan_dev.macaddr="$stom"
	uci set network.wan6.macaddr="$stom"
	uci commit
}

start()
{	
	netcheck = $(uci get dogcom.@dogcom[0].netcheck)
	if [ "$netcheck"x != "1"x ]; then
		return
	fi
	
	tries=0
	echo --- my_watchdog start ---
	while [[ $tries -lt 2 ]]
	do
	        if /bin/ping -c 1 8.8.8.8 >/dev/null
		then
	        	echo --- exit ---
			exit 0
       	 	fi
        	tries=$((tries+1))
        	sleep 3
	done

	sto
	/etc/init.d/network reload

}
