#!/bin/sh /etc/rc.common
#Cpyright by Twizo<1282055288@qq.com>
START=90

stochastic(){
	echo `dd if=/dev/urandom bs=1 count=32 2>/dev/null | md5sum | cut -b 0-12 | sed 's/\(..\)/\1:/g; s/.$//'`
}

minus_mac()
{
	d_mac=$(uci get dogcom.@dogcom[0].mac 2>/dev/null)
	l_mac=$(echo "$d_mac"|sed 's/\(.*\)\(.\)$/\2/')
	ele_mac=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "a" "b" "c" "d" "e" "f" "A" "B" "C" "D" "E" "F")
	for  i  in $(seq 0 21)
	do
		if [ "$l_mac" == "${ele_mac[i]}" ]; then
			if [ "$i" -le "15" ];then
				if [ "$i" -eq "0" ];then
					l_mac=${ele_mac[i+1]}
				else
					l_mac=${ele_mac[i-1]}
				fi
			else
				if [ "$i" -eq "16" ];then
					l_mac=${ele_mac[i-7]}
				else
					l_mac=${ele_mac[i-1]}
				fi
			fi
		fi
	done
	mac=$(echo $d_mac|sed "s/.$/$l_mac/")
	echo $mac
}

sto(){ 
	dogcom_mac=$(uci get dogcom.@dogcom[0].mac 2>/dev/null)
	local stom=$("stochastic")
	if [ -n "$dogcom_mac" ]; then
		stom=$("minus_mac")
	else
		stom=$("stochastic")
	fi
	uci set network.wan.macaddr="$stom"
	uci set network.wan_dev.macaddr="$stom" 2>/dev/null
#	uci set network.wan6.macaddr="$stom"
	uci commit
}

start()
{	
	netcheck = $(uci get dogcom.@dogcom[0].netcheck 2>/dev/null)
	if [ "$netcheck"x != "1"x ]; then
		return
	fi
	
	tries=0
	echo --- my_watchdog start ---
	while [[ $tries -lt 2 ]]
	do
	        if /bin/ping -c 1 8.8.8.8 >/dev/null
		then
			echo "网络连接正常，持续监测中" >> /tmp/dogcom.log
	        	echo --- exit ---
			exit 0
       	 	fi
        	tries=$((tries+1))
        	sleep 3
	done
	echo "网络连接不正常，开始修改mac地址并重新连接" >> /tmp/dogcom.log
	sto
	/etc/init.d/network reload

}
