#!/bin/sh /etc/rc.common
#(c) 2010 ivan_wl
START=90

start() {
	curdir=/etc/dogcom.conf
	touch $curdir
	tmp_server="server= '$(uci get dogcom.@dogcom[0].server )'"
	tmp_pppoe_flag="pppoe_flag='$(uci get dogcom.@dogcom[0].pppoe_flag )'"
	tmp_keep_alive2_flag="keep_alive2_flag='$(uci get dogcom.@dogcom[0].keep_alive2_flag )'"
	echo $tmp_server > $curdir
	echo "$tmp_pppoe_flag" >> "$curdir"
	echo "$tmp_keep_alive2_flag" >> "$curdir"
	enable=$(uci get dogcom.@dogcom[0].enable 2>/dev/null)

	enabledial=$(uci get dogcom.@dogcom[0].enabledial 2>/dev/null)
	ifname=$(uci get network.wan6.ifname 2>/dev/null)
	username=$(uci get dogcom.@dogcom[0].username 2>/dev/null)
	password=$(uci get dogcom.@dogcom[0].password 2>/dev/null)
	macaddr=$(uci get dogcom.@dogcom[0].macaddr 2>/dev/null)	

	if [ "$enable"x = "1"x ]; then
		/etc/init.d/dogcom enable
	else
		/etc/init.d/dogcom disable
		killall dogcom
		return
	fi

	if [ "$enabledial"x != "0"x ]; then
#		echo "$ifname" "$username" "$password"
		uci set network.wan.ifname="$ifname"
		uci set network.wan.proto="pppoe"
		uci set network.wan.username="$username"
		uci set network.wan.password="$password"
		uci commit
	fi

	if [ -n "$macaddr" ]; then
		uci set network.wan.macaddr="$macaddr"
		uci set network.wan6.macaddr="$macaddr"
		uci commit
	fi

	if [ -n "$macaddr" -o "$enabledial"x != "0"x ]; then
		/etc/init.d/network restart
	fi

	if [ -n "$server" ]; then
		config_server="server=$server"
	fi
	if [ -n "$pppoe_flag" ]; then
		config_pppoe_flag="--pppoe-flag=$pppoe_flag"
	fi
	if [ -n "$keep_alive2_flag" ]; then
		config_keep_alive2_flag="--keep-alive2-flag=$keep_alive2_flag"
	fi

	dogcom -m pppoe -c /etc/dogcom.conf -e -d

}
stop()
{
	if [ -n "$(pidof aria2c)" ]; then
		killall dogcom
	fi
	return 0
}
